server:
  port: 9091

spring:
  datasource:
    url: "jdbc:mysql://${db_url}:${db_port}/${db_schema}?allowPublicKeyRetrieval=true&useSSL=false" #"jdbc:mysql://${localhost}:3306/test_db"
    username: ${db_username} #root
    password: ${db_pwd}
  data:
    mongodb:
      host: localhost
      port: 27017
      database: serviceB_db
      authentication-database: admin
      password: root
      username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

kafka:
  bootstrap-servers: http://${kafka}:${kafka_port}
  topic: employee_personal_details
  consumer:
    group-id: employee_details_consumer_group
    auto-offset-reset: earliest
