version: '2.2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:6.1.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  service-a:
    image: service-a
    container_name: service-a
    depends_on:
      - kafka
    ports:
      - 9090:9090
    environment:
       #JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,address=8000,suspend=n
       kafka: kafka
       port: 9092
  
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - ./mydb/mysql_db_data:/var/lib/mysql
    restart: always
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypwd
      MYSQL_DATABASE: kafka_db
      MYSQL_USER: my_db
      MYSQL_PASSWORD: mypwd
  
  service-b:
    image: service-b
    container_name: service-b
    depends_on:
      - service-a
      - mysql
    ports:
      - 9091:9091
      - 8000:8000
    environment:
       kafka: kafka
       kafka_port: 9092
       db_url: mysql
       db_port: 3306
       db_username: root
       db_pwd: mypwd
       db_schema: kafka_db